/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "test.check" instead.
 */

#include <check.h>

#include "my_matrix.h"

START_TEST(my_create_kartest_1) {
  matrix_t example;
  int res_for_sravn_test = my_create_matrix(3, 6, &example);
  int res_for_sravn_test_origin = 0;
  ck_assert_int_eq(res_for_sravn_test, res_for_sravn_test_origin);
  my_remove_matrix(&example);
}
END_TEST

START_TEST(my_create_kartest_2) {
  matrix_t example;
  int res_for_sravn_test = my_create_matrix(45, -7, &example);
  int res_for_sravn_test_origin = 1;
  ck_assert_int_eq(res_for_sravn_test, res_for_sravn_test_origin);
  my_remove_matrix(&example);
}
END_TEST

START_TEST(my_create_kartest_3) {
  matrix_t example;
  int res_for_sravn_test = my_create_matrix(-2, 56, &example);
  int res_for_sravn_test_origin = 1;
  ck_assert_int_eq(res_for_sravn_test, res_for_sravn_test_origin);
  my_remove_matrix(&example);
}
END_TEST

START_TEST(my_create_kartest_4) {
  matrix_t example;
  int res_for_sravn_test = my_create_matrix(24, 0, &example);
  int res_for_sravn_test_origin = 1;
  ck_assert_int_eq(res_for_sravn_test, res_for_sravn_test_origin);
  my_remove_matrix(&example);
}
END_TEST

START_TEST(my_create_kartest_5) {
  matrix_t example;
  int res_for_sravn_test = my_create_matrix(1, 1, &example);
  int res_for_sravn_test_origin = 0;
  ck_assert_int_eq(res_for_sravn_test, res_for_sravn_test_origin);
  my_remove_matrix(&example);
}
END_TEST

START_TEST(my_eq_kartest_1) {
  matrix_t example;
  matrix_t primer;
  int res_for_sravn_test_origin = 0;
  int res_for_sravn_test_1 = my_create_matrix(3, 3, &example);
  int res_for_sravn_test_2 = my_create_matrix(3, 3, &primer);
  example.matrix[0][0] = 0.0;
  example.matrix[0][1] = 1.0;
  example.matrix[0][2] = 2.0;
  example.matrix[1][0] = 3.0;
  example.matrix[1][1] = 4.0;
  example.matrix[1][2] = 5.0;
  example.matrix[2][0] = 6.0;
  example.matrix[2][1] = 7.0;
  example.matrix[2][2] = 8.0;
  primer.matrix[0][0] = 0.0;
  primer.matrix[0][1] = 1.0;
  primer.matrix[0][2] = 2.0;
  primer.matrix[1][0] = 3.0;
  primer.matrix[1][1] = 4.0;
  primer.matrix[1][2] = 5.0;
  primer.matrix[2][0] = 6.0;
  primer.matrix[2][1] = 7.0;
  primer.matrix[2][2] = 8.0;
  int result = my_eq_matrix(&example, &primer);
  int result_origin = SUCCESS;
  ck_assert_int_eq(res_for_sravn_test_1, res_for_sravn_test_origin);
  ck_assert_int_eq(res_for_sravn_test_2, res_for_sravn_test_origin);
  ck_assert_int_eq(result, result_origin);
  my_remove_matrix(&example);
  my_remove_matrix(&primer);
}
END_TEST

START_TEST(my_eq_kartest_2) {
  matrix_t example;
  matrix_t primer;
  int res_for_sravn_test_origin = 0;
  int res_for_sravn_test_1 = my_create_matrix(3, 3, &example);
  int res_for_sravn_test_2 = my_create_matrix(3, 3, &primer);
  example.matrix[0][0] = 987654321.123456789;
  example.matrix[0][1] = 1111111111111.1111111111111;
  example.matrix[0][2] = 2.0;
  example.matrix[1][0] = 3.0000001;
  example.matrix[1][1] = 4.111111111;
  example.matrix[1][2] = 5123454321.5123454321;
  example.matrix[2][0] = 666666666666.0;
  example.matrix[2][1] = 7.0;
  example.matrix[2][2] = 987654321.9123456789;
  primer.matrix[0][0] = 987654321.123456789;
  primer.matrix[0][1] = 1111111111111.1111111111111;
  primer.matrix[0][2] = 2.0;
  primer.matrix[1][0] = 3.0000001;
  primer.matrix[1][1] = 4.111111111;
  primer.matrix[1][2] = 5123454321.5123454321;
  primer.matrix[2][0] = 666666666666.0;
  primer.matrix[2][1] = 7.0;
  primer.matrix[2][2] = 987654321.9123456789;
  int result = my_eq_matrix(&example, &primer);
  int result_origin = SUCCESS;
  ck_assert_int_eq(res_for_sravn_test_1, res_for_sravn_test_origin);
  ck_assert_int_eq(res_for_sravn_test_2, res_for_sravn_test_origin);
  ck_assert_int_eq(result, result_origin);
  my_remove_matrix(&example);
  my_remove_matrix(&primer);
}
END_TEST

START_TEST(my_eq_kartest_3) {
  matrix_t example;
  matrix_t primer;
  int res_for_sravn_test_origin = 0;
  int res_for_sravn_test_1 = my_create_matrix(3, 3, &example);
  int res_for_sravn_test_2 = my_create_matrix(3, 3, &primer);
  example.matrix[0][0] = 987654321.1234567;
  example.matrix[0][1] = 1111111111111.1111111;
  example.matrix[0][2] = 2.0000000;
  example.matrix[1][0] = 3.0000001;
  example.matrix[1][1] = 4.1111111;
  example.matrix[1][2] = 5123454321.5123454;
  example.matrix[2][0] = 666666666666.0000000;
  example.matrix[2][1] = 7.0000000;
  example.matrix[2][2] = 987654321.9123456;
  primer.matrix[0][0] = 987654321.1234567;
  primer.matrix[0][1] = 1111111111111.1111111;
  primer.matrix[0][2] = 2.0000000;
  primer.matrix[1][0] = 3.0000001;
  primer.matrix[1][1] = 4.1111111;
  primer.matrix[1][2] = 5123454321.5123454;
  primer.matrix[2][0] = 666666666666.0000000;
  primer.matrix[2][1] = 7.0000000;
  primer.matrix[2][2] = 987654321.9123456;
  int result = my_eq_matrix(&example, &primer);
  int result_origin = SUCCESS;
  ck_assert_int_eq(res_for_sravn_test_1, res_for_sravn_test_origin);
  ck_assert_int_eq(res_for_sravn_test_2, res_for_sravn_test_origin);
  ck_assert_int_eq(result, result_origin);
  my_remove_matrix(&example);
  my_remove_matrix(&primer);
}
END_TEST

START_TEST(my_eq_kartest_4) {
  matrix_t example;
  matrix_t primer;
  int res_for_sravn_test_origin = 0;
  int res_for_sravn_test_1 = my_create_matrix(3, 3, &example);
  int res_for_sravn_test_2 = my_create_matrix(3, 3, &primer);
  example.matrix[0][0] = 987654321.1234567;
  example.matrix[0][1] = 1111111111111.111111;
  example.matrix[0][2] = 2.000005;
  example.matrix[1][0] = 3.0000001;
  example.matrix[1][1] = 4.1111111;
  example.matrix[1][2] = 5123454321.5123454;
  example.matrix[2][0] = 666666666666.0;
  example.matrix[2][1] = 7.0;
  example.matrix[2][2] = 987654321.9123456;

  primer.matrix[0][0] = 987654321.1234567;
  primer.matrix[0][1] = 1111111111111.111111;
  primer.matrix[0][2] = 2.0;
  primer.matrix[1][0] = 3.0000001;
  primer.matrix[1][1] = 4.1111111;
  primer.matrix[1][2] = 5123454321.5123454;
  primer.matrix[2][0] = 666666666666.0;
  primer.matrix[2][1] = 7.0;
  primer.matrix[2][2] = 987654321.9123456;
  int result = my_eq_matrix(&example, &primer);
  int result_origin = FAILURE;
  ck_assert_int_eq(res_for_sravn_test_1, res_for_sravn_test_origin);
  ck_assert_int_eq(res_for_sravn_test_2, res_for_sravn_test_origin);
  ck_assert_int_eq(result, result_origin);
  my_remove_matrix(&example);
  my_remove_matrix(&primer);
}
END_TEST

START_TEST(my_eq_kar_test_1) {
  matrix_t A;
  my_create_matrix(2, 2, &A);
  A.matrix[0][0] = 3.3333335;
  A.matrix[0][1] = -5;
  A.matrix[1][0] = 6;
  A.matrix[1][1] = -3;
  matrix_t B;
  my_create_matrix(2, 2, &B);
  B.matrix[0][0] = 3.33333356;
  B.matrix[0][1] = -5;
  B.matrix[1][0] = 6;
  B.matrix[1][1] = -3;
  int result = my_eq_matrix(&A, &B);
  ck_assert_int_eq(result, 1);
  my_remove_matrix(&A);
  my_remove_matrix(&B);
}
END_TEST

START_TEST(my_eq_kar_test_2) {
  matrix_t A;
  my_create_matrix(2, 2, &A);
  A.matrix[0][0] = 3.33333357;
  A.matrix[0][1] = -5;
  A.matrix[1][0] = 6;
  A.matrix[1][1] = -3;
  matrix_t B;
  my_create_matrix(2, 2, &B);
  B.matrix[0][0] = 3.33333356;
  B.matrix[0][1] = -5;
  B.matrix[1][0] = 6;
  B.matrix[1][1] = -3;
  int result = my_eq_matrix(&A, &B);
  ck_assert_int_eq(result, 1);
  my_remove_matrix(&A);
  my_remove_matrix(&B);
}
END_TEST

START_TEST(my_eq_kar_test_3) {
  matrix_t A;
  my_create_matrix(2, 2, &A);
  A.matrix[0][0] = 3.0;
  A.matrix[0][1] = -5;
  A.matrix[1][0] = 6;
  A.matrix[1][1] = -3;
  matrix_t B;
  my_create_matrix(2, 2, &B);
  B.matrix[0][0] = 2.0;
  B.matrix[0][1] = -5;
  B.matrix[1][0] = 6;
  B.matrix[1][1] = -3;
  int result = my_eq_matrix(&A, &B);
  ck_assert_int_eq(result, 0);
  my_remove_matrix(&A);
  my_remove_matrix(&B);
}
END_TEST

START_TEST(my_eq_kar_test_4) {
  matrix_t A;
  my_create_matrix(2, 2, &A);
  A.matrix[0][0] = 3.3;
  A.matrix[0][1] = -5;
  A.matrix[1][0] = 6;
  A.matrix[1][1] = 3.33333334;
  matrix_t B;
  my_create_matrix(2, 2, &B);
  B.matrix[0][0] = 3.3;
  B.matrix[0][1] = -5;
  B.matrix[1][0] = 6;
  B.matrix[1][1] = 3.3333335;
  int result = my_eq_matrix(&A, &B);
  ck_assert_int_eq(result, 1);
  my_remove_matrix(&A);
  my_remove_matrix(&B);
}
END_TEST

START_TEST(my_eq_kar_test_5) {
  matrix_t A;
  my_create_matrix(1, 1, &A);
  A.matrix[0][0] = 1;
  matrix_t B;
  my_create_matrix(1, 1, &B);
  B.matrix[0][0] = 1;
  int result = my_eq_matrix(&A, &B);
  ck_assert_int_eq(result, 1);
  my_remove_matrix(&A);
  my_remove_matrix(&B);
}
END_TEST

START_TEST(my_eq_kar_test_6) {
  matrix_t A;
  my_create_matrix(2, 2, &A);
  A.matrix[0][0] = 1;
  A.matrix[0][1] = 1;
  A.matrix[1][0] = 1;
  A.matrix[1][1] = 1;
  matrix_t B;
  my_create_matrix(1, 1, &B);
  B.matrix[0][0] = 1;
  int result = my_eq_matrix(&A, &B);
  ck_assert_int_eq(result, 0);
  my_remove_matrix(&A);
  my_remove_matrix(&B);
}
END_TEST

START_TEST(my_sum_kartest_1) {
  matrix_t example;
  matrix_t primer;
  matrix_t origin;
  matrix_t r;
  int res_for_sravn_test_origin = 0;
  int res_for_sravn_test_1 = my_create_matrix(3, 3, &example);
  int res_for_sravn_test_2 = my_create_matrix(3, 3, &primer);
  int res_for_sravn_test_3 = my_create_matrix(3, 3, &origin);
  example.matrix[0][0] = 0.1;
  example.matrix[0][1] = 0.2;
  example.matrix[0][2] = 0.3;
  example.matrix[1][0] = 0.4;
  example.matrix[1][1] = 0.5;
  example.matrix[1][2] = 0.6;
  example.matrix[2][0] = 0.7;
  example.matrix[2][1] = 0.8;
  example.matrix[2][2] = 0.9;
  primer.matrix[0][0] = 1.0;
  primer.matrix[0][1] = 2.0;
  primer.matrix[0][2] = 3.0;
  primer.matrix[1][0] = 4.0;
  primer.matrix[1][1] = 5.0;
  primer.matrix[1][2] = 6.0;
  primer.matrix[2][0] = 7.0;
  primer.matrix[2][1] = 8.0;
  primer.matrix[2][2] = 9.0;
  origin.matrix[0][0] = 1.1;
  origin.matrix[0][1] = 2.2;
  origin.matrix[0][2] = 3.3;
  origin.matrix[1][0] = 4.4;
  origin.matrix[1][1] = 5.5;
  origin.matrix[1][2] = 6.6;
  origin.matrix[2][0] = 7.7;
  origin.matrix[2][1] = 8.8;
  origin.matrix[2][2] = 9.9;
  int result = my_sum_matrix(&example, &primer, &r);
  ck_assert_int_eq(res_for_sravn_test_1, res_for_sravn_test_origin);
  ck_assert_int_eq(res_for_sravn_test_2, res_for_sravn_test_origin);
  ck_assert_int_eq(res_for_sravn_test_3, res_for_sravn_test_origin);
  ck_assert_int_eq(result, res_for_sravn_test_origin);
  for (int i = 0; i < r.rows; i++) {
    for (int j = 0; j < r.columns; j++) {
      ck_assert_double_eq_tol(origin.matrix[i][j], r.matrix[i][j], MY_EPS);
    }
  }
  my_remove_matrix(&example);
  my_remove_matrix(&primer);
  my_remove_matrix(&r);
  my_remove_matrix(&origin);
}
END_TEST

START_TEST(my_sum_kartest_1_0) {
  matrix_t example;
  matrix_t primer;
  matrix_t origin;
  matrix_t r;
  int res_for_sravn_test_origin = 1;
  my_create_matrix(3, -3, &example);
  my_create_matrix(-3, 3, &primer);
  my_create_matrix(3, 3, &origin);
  int result = my_sum_matrix(&example, &primer, &r);

  ck_assert_int_eq(result, res_for_sravn_test_origin);
  my_remove_matrix(&example);
  my_remove_matrix(&primer);
  my_remove_matrix(&r);
  my_remove_matrix(&origin);
}
END_TEST

START_TEST(my_sum_kartest_2) {
  matrix_t example;
  matrix_t primer;
  matrix_t origin;
  matrix_t r;
  int res_for_sravn_test_origin = 0;
  int res_for_sravn_test_1 = my_create_matrix(3, 3, &example);
  int res_for_sravn_test_2 = my_create_matrix(3, 3, &primer);
  int res_for_sravn_test_3 = my_create_matrix(3, 3, &origin);
  example.matrix[0][0] = 0.1;
  example.matrix[0][1] = 0.2;
  example.matrix[0][2] = 0.3;
  example.matrix[1][0] = 0.4;
  example.matrix[1][1] = 0.5;
  example.matrix[1][2] = 0.6;
  example.matrix[2][0] = 0.7;
  example.matrix[2][1] = 0.8;
  example.matrix[2][2] = 0.9;
  primer.matrix[0][0] = 0.0;
  primer.matrix[0][1] = 0.0;
  primer.matrix[0][2] = 0.0;
  primer.matrix[1][0] = 0.0;
  primer.matrix[1][1] = 0.0;
  primer.matrix[1][2] = 0.0;
  primer.matrix[2][0] = 0.0;
  primer.matrix[2][1] = 0.0;
  primer.matrix[2][2] = 0.0;
  origin.matrix[0][0] = 0.1;
  origin.matrix[0][1] = 0.2;
  origin.matrix[0][2] = 0.3;
  origin.matrix[1][0] = 0.4;
  origin.matrix[1][1] = 0.5;
  origin.matrix[1][2] = 0.6;
  origin.matrix[2][0] = 0.7;
  origin.matrix[2][1] = 0.8;
  origin.matrix[2][2] = 0.9;
  int result = my_sum_matrix(&example, &primer, &r);
  ck_assert_int_eq(res_for_sravn_test_1, res_for_sravn_test_origin);
  ck_assert_int_eq(res_for_sravn_test_2, res_for_sravn_test_origin);
  ck_assert_int_eq(res_for_sravn_test_3, res_for_sravn_test_origin);
  ck_assert_int_eq(result, res_for_sravn_test_origin);
  for (int i = 0; i < r.rows; i++) {
    for (int j = 0; j < r.columns; j++) {
      ck_assert_double_eq_tol(origin.matrix[i][j], r.matrix[i][j], MY_EPS);
    }
  }
  my_remove_matrix(&example);
  my_remove_matrix(&primer);
  my_remove_matrix(&r);
  my_remove_matrix(&origin);
}
END_TEST

START_TEST(my_sum_kartest_3) {
  matrix_t example;
  matrix_t primer;
  matrix_t origin;
  matrix_t r;
  int res_for_sravn_test_origin = 0;
  int res_for_sravn_test_1 = my_create_matrix(3, 3, &example);
  int res_for_sravn_test_2 = my_create_matrix(3, 3, &primer);
  int res_for_sravn_test_3 = my_create_matrix(3, 3, &origin);
  example.matrix[0][0] = 0.1;
  example.matrix[0][1] = 0.2;
  example.matrix[0][2] = 0.3;
  example.matrix[1][0] = 0.4;
  example.matrix[1][1] = 0.5;
  example.matrix[1][2] = 0.6;
  example.matrix[2][0] = 0.7;
  example.matrix[2][1] = 0.8;
  example.matrix[2][2] = 0.9;
  primer.matrix[0][0] = -1.0;
  primer.matrix[0][1] = -2.0;
  primer.matrix[0][2] = -3.0;
  primer.matrix[1][0] = -4.0;
  primer.matrix[1][1] = -5.0;
  primer.matrix[1][2] = -6.0;
  primer.matrix[2][0] = -7.0;
  primer.matrix[2][1] = -8.0;
  primer.matrix[2][2] = -9.0;
  origin.matrix[0][0] = -0.9;
  origin.matrix[0][1] = -1.8;
  origin.matrix[0][2] = -2.7;
  origin.matrix[1][0] = -3.6;
  origin.matrix[1][1] = -4.5;
  origin.matrix[1][2] = -5.4;
  origin.matrix[2][0] = -6.3;
  origin.matrix[2][1] = -7.2;
  origin.matrix[2][2] = -8.1;
  int result = my_sum_matrix(&example, &primer, &r);
  ck_assert_int_eq(res_for_sravn_test_1, res_for_sravn_test_origin);
  ck_assert_int_eq(res_for_sravn_test_2, res_for_sravn_test_origin);
  ck_assert_int_eq(res_for_sravn_test_3, res_for_sravn_test_origin);
  ck_assert_int_eq(result, res_for_sravn_test_origin);
  for (int i = 0; i < r.rows; i++) {
    for (int j = 0; j < r.columns; j++) {
      ck_assert_double_eq_tol(origin.matrix[i][j], r.matrix[i][j], MY_EPS);
    }
  }
  my_remove_matrix(&example);
  my_remove_matrix(&primer);
  my_remove_matrix(&r);
  my_remove_matrix(&origin);
}
END_TEST

START_TEST(my_sum_kar_test_1) {
  matrix_t result, B, A;
  my_create_matrix(2, 2, &A);
  my_create_matrix(2, 2, &B);
  A.matrix[0][0] = 1;
  A.matrix[0][1] = 1;
  A.matrix[1][0] = 1;
  A.matrix[1][1] = 1;
  B.matrix[0][0] = 3;
  B.matrix[0][1] = 3;
  B.matrix[1][0] = 3;
  B.matrix[1][1] = 3;
  int res_for_sravn_test = my_sum_matrix(&A, &B, &result);
  int res_for_sravn_test_origin = 0;
  ck_assert_int_eq(res_for_sravn_test, res_for_sravn_test_origin);
  for (int i = 0; i < A.rows; i++) {
    for (int j = 0; j < B.columns; j++) {
      ck_assert_int_eq(result.matrix[i][j], 4);
    }
  }
  my_remove_matrix(&A);
  my_remove_matrix(&B);
  my_remove_matrix(&result);
}
END_TEST

START_TEST(my_sum_kar_test_2) {
  matrix_t result, B, A;
  my_create_matrix(2, 2, &A);
  my_create_matrix(2, 2, &B);
  A.matrix[0][0] = 0;
  A.matrix[0][1] = 0;
  A.matrix[1][0] = 0;
  A.matrix[1][1] = 0;
  B.matrix[0][0] = 0;
  B.matrix[0][1] = 0;
  B.matrix[1][0] = 0;
  B.matrix[1][1] = 0;
  int res_for_sravn_test = my_sum_matrix(&A, &B, &result);
  int res_for_sravn_test_origin = 0;
  ck_assert_int_eq(res_for_sravn_test, res_for_sravn_test_origin);
  for (int i = 0; i < A.rows; i++) {
    for (int j = 0; j < B.columns; j++) {
      ck_assert_int_eq(result.matrix[i][j], 0);
    }
  }
  my_remove_matrix(&A);
  my_remove_matrix(&B);
  my_remove_matrix(&result);
}
END_TEST

START_TEST(my_sum_kar_test_3) {
  matrix_t result, B, A;
  my_create_matrix(1, 2, &A);
  my_create_matrix(2, 2, &B);
  A.matrix[0][0] = 1;
  A.matrix[0][1] = 1;
  B.matrix[0][0] = 3;
  B.matrix[0][1] = 3;
  B.matrix[1][0] = 3;
  B.matrix[1][1] = 3;
  int res_for_sravn_test = my_sum_matrix(&A, &B, &result);
  int res_for_sravn_test_origin = 2;
  ck_assert_int_eq(res_for_sravn_test, res_for_sravn_test_origin);
  my_remove_matrix(&A);
  my_remove_matrix(&B);
  my_remove_matrix(&result);
}
END_TEST

START_TEST(my_sum_kar_test_4) {
  matrix_t result, res_origin, B, A;
  my_create_matrix(4, 4, &A);
  my_create_matrix(4, 4, &B);
  my_create_matrix(4, 4, &res_origin);
  A.matrix[0][0] = 2;
  A.matrix[0][1] = 5;
  A.matrix[0][2] = 7;
  A.matrix[0][3] = -4;
  A.matrix[1][0] = 6;
  A.matrix[1][1] = 3;
  A.matrix[1][2] = 4;
  A.matrix[1][3] = 14;
  A.matrix[2][0] = 5;
  A.matrix[2][1] = -2;
  A.matrix[2][2] = -3;
  A.matrix[2][3] = -1;
  A.matrix[3][0] = 10;
  A.matrix[3][1] = 3;
  A.matrix[3][2] = 9;
  A.matrix[3][3] = -3;
  B.matrix[0][0] = 8;
  B.matrix[0][1] = 8;
  B.matrix[0][2] = 3;
  B.matrix[0][3] = 5;
  B.matrix[1][0] = -7;
  B.matrix[1][1] = 7;
  B.matrix[1][2] = 1;
  B.matrix[1][3] = 1;
  B.matrix[2][0] = 7;
  B.matrix[2][1] = 3;
  B.matrix[2][2] = 4;
  B.matrix[2][3] = -4;
  B.matrix[3][0] = 10;
  B.matrix[3][1] = 3;
  B.matrix[3][2] = 9;
  B.matrix[3][3] = -3;
  res_origin.matrix[0][0] = 10;
  res_origin.matrix[0][1] = 13;
  res_origin.matrix[0][2] = 10;
  res_origin.matrix[0][3] = 1;
  res_origin.matrix[1][0] = -1;
  res_origin.matrix[1][1] = 10;
  res_origin.matrix[1][2] = 5;
  res_origin.matrix[1][3] = 15;
  res_origin.matrix[2][0] = 12;
  res_origin.matrix[2][1] = 1;
  res_origin.matrix[2][2] = 1;
  res_origin.matrix[2][3] = -5;
  res_origin.matrix[3][0] = 20;
  res_origin.matrix[3][1] = 6;
  res_origin.matrix[3][2] = 18;
  res_origin.matrix[3][3] = -6;
  int res_for_sravn_test = my_sum_matrix(&A, &B, &result);
  int res_for_sravn_test_origin = 0;
  ck_assert_int_eq(res_for_sravn_test, res_for_sravn_test_origin);
  for (int i = 0; i < res_origin.rows; i++) {
    for (int j = 0; j < res_origin.columns; j++) {
      ck_assert_uint_eq(res_origin.matrix[i][j], result.matrix[i][j]);
    }
  }
  my_remove_matrix(&A);
  my_remove_matrix(&B);
  my_remove_matrix(&result);
  my_remove_matrix(&res_origin);
}
END_TEST

START_TEST(my_sum_kar_test_5) {
  matrix_t result, res_origin, B, A;
  my_create_matrix(2, 2, &A);
  my_create_matrix(2, 2, &B);
  my_create_matrix(2, 2, &res_origin);
  A.matrix[0][0] = 2.987654;
  A.matrix[0][1] = -5.3456;
  A.matrix[1][0] = 6.23;
  A.matrix[1][1] = -3.9292;
  B.matrix[0][0] = 4.838;
  B.matrix[0][1] = 8.0987;
  B.matrix[1][0] = -8;
  B.matrix[1][1] = -0.921;
  res_origin.matrix[0][0] = 7.825654;
  res_origin.matrix[0][1] = 2.7531;
  res_origin.matrix[1][0] = -1.77;
  res_origin.matrix[1][1] = -4.8502;
  int res_for_sravn_test = my_sum_matrix(&A, &B, &result);
  int res_for_sravn_test_origin = 0;
  ck_assert_int_eq(res_for_sravn_test, res_for_sravn_test_origin);
  for (int i = 0; i < res_origin.rows; i++) {
    for (int j = 0; j < res_origin.columns; j++) {
      ck_assert_uint_eq(res_origin.matrix[i][j], result.matrix[i][j]);
    }
  }
  my_remove_matrix(&A);
  my_remove_matrix(&B);
  my_remove_matrix(&result);
  my_remove_matrix(&res_origin);
}
END_TEST

START_TEST(my_sum_kar_test_6) {
  matrix_t result, res_origin, B, A;
  my_create_matrix(5, 5, &A);
  my_create_matrix(5, 5, &B);
  my_create_matrix(5, 5, &res_origin);
  for (int i = 0; i < A.rows; i++) {
    for (int j = 0; j < A.columns; j++) {
      A.matrix[i][j] = i;
    }
  }
  for (int i = 0; i < B.rows; i++) {
    for (int j = 0; j < B.columns; j++) {
      B.matrix[i][j] = i;
    }
  }
  for (int i = 0; i < res_origin.rows; i++) {
    for (int j = 0; j < res_origin.columns; j++) {
      res_origin.matrix[i][j] = i * 2;
    }
  }
  int res_for_sravn_test = my_sum_matrix(&A, &B, &result);
  int res_for_sravn_test_origin = 0;
  ck_assert_int_eq(res_for_sravn_test, res_for_sravn_test_origin);
  for (int i = 0; i < res_origin.rows; i++) {
    for (int j = 0; j < res_origin.columns; j++) {
      ck_assert_uint_eq(res_origin.matrix[i][j], result.matrix[i][j]);
    }
  }
  my_remove_matrix(&A);
  my_remove_matrix(&B);
  my_remove_matrix(&result);
  my_remove_matrix(&res_origin);
}
END_TEST

START_TEST(my_sum_kar_test_7) {
  matrix_t result, res_origin, B, A;
  my_create_matrix(5, 4, &A);
  my_create_matrix(5, 4, &B);
  my_create_matrix(5, 4, &res_origin);
  for (int i = 0; i < A.rows; i++) {
    for (int j = 0; j < A.columns; j++) {
      A.matrix[i][j] = i;
      res_origin.matrix[i][j] = i;
    }
  }
  int res_for_sravn_test = my_sum_matrix(&A, &B, &result);
  int res_for_sravn_test_origin = 0;
  ck_assert_int_eq(res_for_sravn_test, res_for_sravn_test_origin);
  for (int i = 0; i < res_origin.rows; i++) {
    for (int j = 0; j < res_origin.columns; j++) {
      ck_assert_uint_eq(res_origin.matrix[i][j], result.matrix[i][j]);
    }
  }
  my_remove_matrix(&A);
  my_remove_matrix(&B);
  my_remove_matrix(&result);
  my_remove_matrix(&res_origin);
}
END_TEST

START_TEST(my_sum_kar_test_8) {
  matrix_t result, B, A;
  my_create_matrix(5, 5, &A);
  my_create_matrix(5, 4, &B);
  int res_for_sravn_test = my_sum_matrix(&A, &B, &result);
  int res_for_sravn_test_origin = 2;
  ck_assert_int_eq(res_for_sravn_test, res_for_sravn_test_origin);
  my_remove_matrix(&A);
  my_remove_matrix(&B);
  my_remove_matrix(&result);
}
END_TEST

START_TEST(my_sub_kartest_1) {
  matrix_t example;
  matrix_t primer;
  matrix_t origin;
  matrix_t r;
  int res_for_sravn_test_origin = 0;
  int res_for_sravn_test_1 = my_create_matrix(3, 3, &example);
  int res_for_sravn_test_2 = my_create_matrix(3, 3, &primer);
  int res_for_sravn_test_3 = my_create_matrix(3, 3, &origin);
  example.matrix[0][0] = 0.1;
  example.matrix[0][1] = 0.2;
  example.matrix[0][2] = 0.3;
  example.matrix[1][0] = 0.4;
  example.matrix[1][1] = 0.5;
  example.matrix[1][2] = 0.6;
  example.matrix[2][0] = 0.7;
  example.matrix[2][1] = 0.8;
  example.matrix[2][2] = 0.9;
  primer.matrix[0][0] = 1.0;
  primer.matrix[0][1] = 2.0;
  primer.matrix[0][2] = 3.0;
  primer.matrix[1][0] = 4.0;
  primer.matrix[1][1] = 5.0;
  primer.matrix[1][2] = 6.0;
  primer.matrix[2][0] = 7.0;
  primer.matrix[2][1] = 8.0;
  primer.matrix[2][2] = 9.0;
  origin.matrix[0][0] = -0.9;
  origin.matrix[0][1] = -1.8;
  origin.matrix[0][2] = -2.7;
  origin.matrix[1][0] = -3.6;
  origin.matrix[1][1] = -4.5;
  origin.matrix[1][2] = -5.4;
  origin.matrix[2][0] = -6.3;
  origin.matrix[2][1] = -7.2;
  origin.matrix[2][2] = -8.1;
  int result = my_sub_matrix(&example, &primer, &r);
  ck_assert_int_eq(res_for_sravn_test_1, res_for_sravn_test_origin);
  ck_assert_int_eq(res_for_sravn_test_2, res_for_sravn_test_origin);
  ck_assert_int_eq(res_for_sravn_test_3, res_for_sravn_test_origin);
  ck_assert_int_eq(result, res_for_sravn_test_origin);
  for (int i = 0; i < r.rows; i++) {
    for (int j = 0; j < r.columns; j++) {
      ck_assert_double_eq_tol(origin.matrix[i][j], r.matrix[i][j], MY_EPS);
    }
  }
  my_remove_matrix(&example);
  my_remove_matrix(&primer);
  my_remove_matrix(&r);
  my_remove_matrix(&origin);
}
END_TEST

START_TEST(my_sub_kartest_2) {
  matrix_t example;
  matrix_t primer;
  matrix_t origin;
  matrix_t r;
  int res_for_sravn_test_origin = 0;
  int res_for_sravn_test_1 = my_create_matrix(3, 3, &example);
  int res_for_sravn_test_2 = my_create_matrix(3, 3, &primer);
  int res_for_sravn_test_3 = my_create_matrix(3, 3, &origin);
  example.matrix[0][0] = 0.1;
  example.matrix[0][1] = 0.2;
  example.matrix[0][2] = 0.3;
  example.matrix[1][0] = 0.4;
  example.matrix[1][1] = 0.5;
  example.matrix[1][2] = 0.6;
  example.matrix[2][0] = 0.7;
  example.matrix[2][1] = 0.8;
  example.matrix[2][2] = 0.9;
  primer.matrix[0][0] = 0.0;
  primer.matrix[0][1] = 0.0;
  primer.matrix[0][2] = 0.0;
  primer.matrix[1][0] = 0.0;
  primer.matrix[1][1] = 0.0;
  primer.matrix[1][2] = 0.0;
  primer.matrix[2][0] = 0.0;
  primer.matrix[2][1] = 0.0;
  primer.matrix[2][2] = 0.0;
  origin.matrix[0][0] = 0.1;
  origin.matrix[0][1] = 0.2;
  origin.matrix[0][2] = 0.3;
  origin.matrix[1][0] = 0.4;
  origin.matrix[1][1] = 0.5;
  origin.matrix[1][2] = 0.6;
  origin.matrix[2][0] = 0.7;
  origin.matrix[2][1] = 0.8;
  origin.matrix[2][2] = 0.9;
  int result = my_sub_matrix(&example, &primer, &r);
  ck_assert_int_eq(res_for_sravn_test_1, res_for_sravn_test_origin);
  ck_assert_int_eq(res_for_sravn_test_2, res_for_sravn_test_origin);
  ck_assert_int_eq(res_for_sravn_test_3, res_for_sravn_test_origin);
  ck_assert_int_eq(result, res_for_sravn_test_origin);
  for (int i = 0; i < r.rows; i++) {
    for (int j = 0; j < r.columns; j++) {
      ck_assert_double_eq_tol(origin.matrix[i][j], r.matrix[i][j], MY_EPS);
    }
  }
  my_remove_matrix(&example);
  my_remove_matrix(&primer);
  my_remove_matrix(&r);
  my_remove_matrix(&origin);
}
END_TEST

START_TEST(my_sub_kartest_3) {
  matrix_t example;
  matrix_t primer;
  matrix_t origin;
  matrix_t r;
  int res_for_sravn_test_origin = 0;
  int res_for_sravn_test_1 = my_create_matrix(3, 3, &example);
  int res_for_sravn_test_2 = my_create_matrix(3, 3, &primer);
  int res_for_sravn_test_3 = my_create_matrix(3, 3, &origin);
  example.matrix[0][0] = 0.1;
  example.matrix[0][1] = 0.2;
  example.matrix[0][2] = 0.3;
  example.matrix[1][0] = 0.4;
  example.matrix[1][1] = 0.5;
  example.matrix[1][2] = 0.6;
  example.matrix[2][0] = 0.7;
  example.matrix[2][1] = 0.8;
  example.matrix[2][2] = 0.9;
  primer.matrix[0][0] = 1.0;
  primer.matrix[0][1] = 2.0;
  primer.matrix[0][2] = 3.0;
  primer.matrix[1][0] = 4.0;
  primer.matrix[1][1] = 5.0;
  primer.matrix[1][2] = 6.0;
  primer.matrix[2][0] = 7.0;
  primer.matrix[2][1] = 8.0;
  primer.matrix[2][2] = 9.0;
  origin.matrix[0][0] = -0.9;
  origin.matrix[0][1] = -1.8;
  origin.matrix[0][2] = -2.7;
  origin.matrix[1][0] = -3.6;
  origin.matrix[1][1] = -4.5;
  origin.matrix[1][2] = -5.4;
  origin.matrix[2][0] = -6.3;
  origin.matrix[2][1] = -7.2;
  origin.matrix[2][2] = -8.1;
  int result = my_sub_matrix(&example, &primer, &r);
  ck_assert_int_eq(res_for_sravn_test_1, res_for_sravn_test_origin);
  ck_assert_int_eq(res_for_sravn_test_2, res_for_sravn_test_origin);
  ck_assert_int_eq(res_for_sravn_test_3, res_for_sravn_test_origin);
  ck_assert_int_eq(result, res_for_sravn_test_origin);
  for (int i = 0; i < r.rows; i++) {
    for (int j = 0; j < r.columns; j++) {
      ck_assert_double_eq_tol(origin.matrix[i][j], r.matrix[i][j], MY_EPS);
    }
  }
  my_remove_matrix(&example);
  my_remove_matrix(&primer);
  my_remove_matrix(&r);
  my_remove_matrix(&origin);
}
END_TEST

START_TEST(my_sub_kartest_4) {
  matrix_t example;
  matrix_t primer;
  matrix_t origin;
  matrix_t r;
  int res_for_sravn_test_origin = 0;
  int res_for_sravn_test_1 = my_create_matrix(3, 3, &example);
  int res_for_sravn_test_2 = my_create_matrix(3, 3, &primer);
  int res_for_sravn_test_3 = my_create_matrix(3, 3, &origin);
  example.matrix[0][0] = 0.1;
  example.matrix[0][1] = 0.2;
  example.matrix[0][2] = 0.3;
  example.matrix[1][0] = 0.4;
  example.matrix[1][1] = 0.5;
  example.matrix[1][2] = 0.6;
  example.matrix[2][0] = 0.7;
  example.matrix[2][1] = 0.8;
  example.matrix[2][2] = 0.9;
  primer.matrix[0][0] = 0.0;
  primer.matrix[0][1] = 0.0;
  primer.matrix[0][2] = 0.0;
  primer.matrix[1][0] = 0.0;
  primer.matrix[1][1] = 0.0;
  primer.matrix[1][2] = 0.0;
  primer.matrix[2][0] = 0.0;
  primer.matrix[2][1] = 0.0;
  primer.matrix[2][2] = 0.0;
  origin.matrix[0][0] = 0.1;
  origin.matrix[0][1] = 0.2;
  origin.matrix[0][2] = 0.3;
  origin.matrix[1][0] = 0.4;
  origin.matrix[1][1] = 0.5;
  origin.matrix[1][2] = 0.6;
  origin.matrix[2][0] = 0.7;
  origin.matrix[2][1] = 0.8;
  origin.matrix[2][2] = 0.9;
  int result = my_sub_matrix(&primer, &example, &r);
  ck_assert_int_eq(res_for_sravn_test_1, res_for_sravn_test_origin);
  ck_assert_int_eq(res_for_sravn_test_2, res_for_sravn_test_origin);
  ck_assert_int_eq(res_for_sravn_test_3, res_for_sravn_test_origin);
  ck_assert_int_eq(result, res_for_sravn_test_origin);
  for (int i = 0; i < r.rows; i++) {
    for (int j = 0; j < r.columns; j++) {
      ck_assert_double_eq_tol(-(origin.matrix[i][j]), r.matrix[i][j], MY_EPS);
    }
  }
  my_remove_matrix(&example);
  my_remove_matrix(&primer);
  my_remove_matrix(&r);
  my_remove_matrix(&origin);
}
END_TEST

START_TEST(my_sub_kar_test_1) {
  matrix_t result, B, A;
  my_create_matrix(2, 2, &A);
  my_create_matrix(2, 2, &B);
  A.matrix[0][0] = 1;
  A.matrix[0][1] = 1;
  A.matrix[1][0] = 1;
  A.matrix[1][1] = 1;
  B.matrix[0][0] = 3;
  B.matrix[0][1] = 3;
  B.matrix[1][0] = 3;
  B.matrix[1][1] = 3;
  int res_for_sravn_test = my_sub_matrix(&A, &B, &result);
  int res_for_sravn_test_origin = 0;
  ck_assert_int_eq(res_for_sravn_test, res_for_sravn_test_origin);
  for (int i = 0; i < A.rows; i++) {
    for (int j = 0; j < B.columns; j++) {
      ck_assert_int_eq(result.matrix[i][j], -2);
    }
  }
  my_remove_matrix(&A);
  my_remove_matrix(&B);
  my_remove_matrix(&result);
}
END_TEST

START_TEST(my_sub_kar_test_2) {
  matrix_t result, B, A;
  my_create_matrix(2, 2, &A);
  my_create_matrix(2, 2, &B);
  A.matrix[0][0] = 0;
  A.matrix[0][1] = 0;
  A.matrix[1][0] = 0;
  A.matrix[1][1] = 0;
  B.matrix[0][0] = 0;
  B.matrix[0][1] = 0;
  B.matrix[1][0] = 0;
  B.matrix[1][1] = 0;
  int res_for_sravn_test = my_sub_matrix(&A, &B, &result);
  int res_for_sravn_test_origin = 0;
  ck_assert_int_eq(res_for_sravn_test, res_for_sravn_test_origin);
  for (int i = 0; i < A.rows; i++) {
    for (int j = 0; j < B.columns; j++) {
      ck_assert_int_eq(result.matrix[i][j], 0);
    }
  }
  my_remove_matrix(&A);
  my_remove_matrix(&B);
  my_remove_matrix(&result);
}
END_TEST

START_TEST(my_sub_kar_test_3) {
  matrix_t result, B, A;
  my_create_matrix(1, 2, &A);
  my_create_matrix(2, 2, &B);
  A.matrix[0][0] = 1;
  A.matrix[0][1] = 1;
  B.matrix[0][0] = 3;
  B.matrix[0][1] = 3;
  B.matrix[1][0] = 3;
  B.matrix[1][1] = 3;
  int res_for_sravn_test = my_sub_matrix(&A, &B, &result);
  int res_for_sravn_test_origin = 2;
  ck_assert_int_eq(res_for_sravn_test, res_for_sravn_test_origin);
  my_remove_matrix(&A);
  my_remove_matrix(&B);
  my_remove_matrix(&result);
}
END_TEST

START_TEST(my_sub_kar_test_4) {
  matrix_t result, B, A;
  my_create_matrix(-2, 2, &A);
  my_create_matrix(2, 2, &B);
  int res_for_sravn_test = my_sub_matrix(&A, &B, &result);
  int res_for_sravn_test_origin = 1;
  ck_assert_int_eq(res_for_sravn_test, res_for_sravn_test_origin);
  my_remove_matrix(&A);
  my_remove_matrix(&B);
  my_remove_matrix(&result);
}
END_TEST

START_TEST(my_sub_kar_test_5) {
  matrix_t result, B, A;
  my_create_matrix(2, 2, &A);
  my_create_matrix(-2, 2, &B);
  int res_for_sravn_test = my_sub_matrix(&A, &B, &result);
  int res_for_sravn_test_origin = 1;
  ck_assert_int_eq(res_for_sravn_test, res_for_sravn_test_origin);
  my_remove_matrix(&A);
  my_remove_matrix(&B);
  my_remove_matrix(&result);
}
END_TEST

START_TEST(my_sub_kar_test_6) {
  matrix_t result, res_origin, B, A;
  my_create_matrix(4, 4, &A);
  my_create_matrix(4, 4, &B);
  my_create_matrix(4, 4, &res_origin);
  A.matrix[0][0] = 2;
  A.matrix[0][1] = 5;
  A.matrix[0][2] = 7;
  A.matrix[0][3] = -4;
  A.matrix[1][0] = 6;
  A.matrix[1][1] = 3;
  A.matrix[1][2] = 4;
  A.matrix[1][3] = 14;
  A.matrix[2][0] = 5;
  A.matrix[2][1] = -2;
  A.matrix[2][2] = -3;
  A.matrix[2][3] = -1;
  A.matrix[3][0] = 10;
  A.matrix[3][1] = 3;
  A.matrix[3][2] = 9;
  A.matrix[3][3] = -3;
  B.matrix[0][0] = 8;
  B.matrix[0][1] = 8;
  B.matrix[0][2] = 3;
  B.matrix[0][3] = 5;
  B.matrix[1][0] = -7;
  B.matrix[1][1] = 7;
  B.matrix[1][2] = 1;
  B.matrix[1][3] = 1;
  B.matrix[2][0] = 7;
  B.matrix[2][1] = 3;
  B.matrix[2][2] = 4;
  B.matrix[2][3] = -4;
  B.matrix[3][0] = 10;
  B.matrix[3][1] = 3;
  B.matrix[3][2] = 9;
  B.matrix[3][3] = -3;
  res_origin.matrix[0][0] = -6;
  res_origin.matrix[0][1] = -3;
  res_origin.matrix[0][2] = 4;
  res_origin.matrix[0][3] = -9;
  res_origin.matrix[1][0] = 13;
  res_origin.matrix[1][1] = -4;
  res_origin.matrix[1][2] = 3;
  res_origin.matrix[1][3] = 13;
  res_origin.matrix[2][0] = -2;
  res_origin.matrix[2][1] = -5;
  res_origin.matrix[2][2] = -7;
  res_origin.matrix[2][3] = 3;
  res_origin.matrix[3][0] = 0;
  res_origin.matrix[3][1] = 0;
  res_origin.matrix[3][2] = 0;
  res_origin.matrix[3][3] = 0;
  int res_for_sravn_test = my_sub_matrix(&A, &B, &result);
  int res_for_sravn_test_origin = 0;
  ck_assert_int_eq(res_for_sravn_test, res_for_sravn_test_origin);
  for (int i = 0; i < res_origin.rows; i++) {
    for (int j = 0; j < res_origin.columns; j++) {
      ck_assert_uint_eq(res_origin.matrix[i][j], result.matrix[i][j]);
    }
  }
  my_remove_matrix(&A);
  my_remove_matrix(&B);
  my_remove_matrix(&result);
  my_remove_matrix(&res_origin);
}
END_TEST

START_TEST(my_sub_kar_test_7) {
  matrix_t result, res_origin, B, A;
  my_create_matrix(2, 2, &A);
  my_create_matrix(2, 2, &B);
  my_create_matrix(2, 2, &res_origin);
  A.matrix[0][0] = 2.987654;
  A.matrix[0][1] = -5.3456;
  A.matrix[1][0] = 6.23;
  A.matrix[1][1] = -3.9292;
  B.matrix[0][0] = 4.838;
  B.matrix[0][1] = 8.0987;
  B.matrix[1][0] = -8;
  B.matrix[1][1] = -0.921;
  res_origin.matrix[0][0] = -1.850346;
  res_origin.matrix[0][1] = -13.4443;
  res_origin.matrix[1][0] = 14.23;
  res_origin.matrix[1][1] = -3.0082;
  int res_for_sravn_test = my_sub_matrix(&A, &B, &result);
  int res_for_sravn_test_origin = 0;
  ck_assert_int_eq(res_for_sravn_test, res_for_sravn_test_origin);
  for (int i = 0; i < res_origin.rows; i++) {
    for (int j = 0; j < res_origin.columns; j++) {
      ck_assert_uint_eq(res_origin.matrix[i][j], result.matrix[i][j]);
    }
  }
  my_remove_matrix(&A);
  my_remove_matrix(&B);
  my_remove_matrix(&result);
  my_remove_matrix(&res_origin);
}
END_TEST

START_TEST(my_sub_kar_test_8) {
  matrix_t result, res_origin, B, A;
  my_create_matrix(5, 5, &A);
  my_create_matrix(5, 5, &B);
  my_create_matrix(5, 5, &res_origin);
  for (int i = 0; i < A.rows; i++) {
    for (int j = 0; j < A.columns; j++) {
      A.matrix[i][j] = 4 * i;
    }
  }
  for (int i = 0; i < B.rows; i++) {
    for (int j = 0; j < B.columns; j++) {
      B.matrix[i][j] = 2 * i;
    }
  }
  for (int i = 0; i < res_origin.rows; i++) {
    for (int j = 0; j < res_origin.columns; j++) {
      res_origin.matrix[i][j] = i * 2;
    }
  }
  int res_for_sravn_test = my_sub_matrix(&A, &B, &result);
  int res_for_sravn_test_origin = 0;
  ck_assert_int_eq(res_for_sravn_test, res_for_sravn_test_origin);
  for (int i = 0; i < res_origin.rows; i++) {
    for (int j = 0; j < res_origin.columns; j++) {
      ck_assert_uint_eq(res_origin.matrix[i][j], result.matrix[i][j]);
    }
  }
  my_remove_matrix(&A);
  my_remove_matrix(&B);
  my_remove_matrix(&result);
  my_remove_matrix(&res_origin);
}
END_TEST

START_TEST(my_sub_kar_test_9) {
  matrix_t result, res_origin, B, A;
  my_create_matrix(5, 4, &A);
  my_create_matrix(5, 4, &B);
  my_create_matrix(5, 4, &res_origin);
  for (int i = 0; i < A.rows; i++) {
    for (int j = 0; j < A.columns; j++) {
      A.matrix[i][j] = i;
      res_origin.matrix[i][j] = i;
    }
  }
  int res_for_sravn_test = my_sub_matrix(&A, &B, &result);
  int res_for_sravn_test_origin = 0;
  ck_assert_int_eq(res_for_sravn_test, res_for_sravn_test_origin);
  for (int i = 0; i < res_origin.rows; i++) {
    for (int j = 0; j < res_origin.columns; j++) {
      ck_assert_uint_eq(res_origin.matrix[i][j], result.matrix[i][j]);
    }
  }
  my_remove_matrix(&A);
  my_remove_matrix(&B);
  my_remove_matrix(&result);
  my_remove_matrix(&res_origin);
}
END_TEST

START_TEST(my_mul_num_kartest_1) {
  matrix_t example;
  matrix_t origin;
  matrix_t r;
  double num = 2.0;
  int res_for_sravn_test_origin = 0;
  int res_for_sravn_test_1 = my_create_matrix(3, 3, &example);
  int res_for_sravn_test_2 = my_create_matrix(3, 3, &origin);
  example.matrix[0][0] = 0.1;
  example.matrix[0][1] = 0.2;
  example.matrix[0][2] = 0.3;
  example.matrix[1][0] = 0.4;
  example.matrix[1][1] = 0.5;
  example.matrix[1][2] = 0.6;
  example.matrix[2][0] = 0.7;
  example.matrix[2][1] = 0.8;
  example.matrix[2][2] = 0.9;
  origin.matrix[0][0] = 0.2;
  origin.matrix[0][1] = 0.4;
  origin.matrix[0][2] = 0.6;
  origin.matrix[1][0] = 0.8;
  origin.matrix[1][1] = 1.0;
  origin.matrix[1][2] = 1.2;
  origin.matrix[2][0] = 1.4;
  origin.matrix[2][1] = 1.6;
  origin.matrix[2][2] = 1.8;
  int result = my_mult_number(&example, num, &r);
  ck_assert_int_eq(res_for_sravn_test_1, res_for_sravn_test_origin);
  ck_assert_int_eq(res_for_sravn_test_2, res_for_sravn_test_origin);
  ck_assert_int_eq(result, res_for_sravn_test_origin);
  for (int i = 0; i < r.rows; i++) {
    for (int j = 0; j < r.columns; j++) {
      ck_assert_double_eq_tol(origin.matrix[i][j], r.matrix[i][j], MY_EPS);
    }
  }
  my_remove_matrix(&example);
  my_remove_matrix(&r);
  my_remove_matrix(&origin);
}
END_TEST

START_TEST(my_mul_num_kartest_1_0) {
  matrix_t example;
  matrix_t origin;
  matrix_t r;
  double num = 2.0;
  int res_for_sravn_test_origin = 1;
  my_create_matrix(-3, 3, &example);
  my_create_matrix(3, 3, &origin);
  int result = my_mult_number(&example, num, &r);
  ck_assert_int_eq(result, res_for_sravn_test_origin);
  my_remove_matrix(&example);
  my_remove_matrix(&r);
  my_remove_matrix(&origin);
}
END_TEST

START_TEST(my_mul_num_kartest_2) {
  matrix_t example;
  matrix_t r;
  double num = 0.0;
  int res_for_sravn_test_origin = 0;
  int res_for_sravn_test_1 = my_create_matrix(3, 3, &example);
  example.matrix[0][0] = 0.1;
  example.matrix[0][1] = 0.2;
  example.matrix[0][2] = 0.3;
  example.matrix[1][0] = 0.4;
  example.matrix[1][1] = 0.5;
  example.matrix[1][2] = 0.6;
  example.matrix[2][0] = 0.7;
  example.matrix[2][1] = 0.8;
  example.matrix[2][2] = 0.9;
  int result = my_mult_number(&example, num, &r);
  ck_assert_int_eq(res_for_sravn_test_1, res_for_sravn_test_origin);
  ck_assert_int_eq(result, res_for_sravn_test_origin);
  for (int i = 0; i < r.rows; i++) {
    for (int j = 0; j < r.columns; j++) {
      ck_assert_double_eq_tol(0.0, r.matrix[i][j], MY_EPS);
    }
  }
  my_remove_matrix(&example);
  my_remove_matrix(&r);
}
END_TEST

START_TEST(my_mul_num_kartest_3) {
  matrix_t example;
  matrix_t r;
  double num = 1.0;
  int res_for_sravn_test_origin = 0;
  int res_for_sravn_test_1 = my_create_matrix(3, 3, &example);
  example.matrix[0][0] = 0.1;
  example.matrix[0][1] = 0.2;
  example.matrix[0][2] = 0.3;
  example.matrix[1][0] = 0.4;
  example.matrix[1][1] = 0.5;
  example.matrix[1][2] = 0.6;
  example.matrix[2][0] = 0.7;
  example.matrix[2][1] = 0.8;
  example.matrix[2][2] = 0.9;
  int result = my_mult_number(&example, num, &r);
  ck_assert_int_eq(res_for_sravn_test_1, res_for_sravn_test_origin);
  ck_assert_int_eq(result, res_for_sravn_test_origin);
  for (int i = 0; i < r.rows; i++) {
    for (int j = 0; j < r.columns; j++) {
      ck_assert_double_eq_tol(example.matrix[i][j], r.matrix[i][j], MY_EPS);
    }
  }
  my_remove_matrix(&example);
  my_remove_matrix(&r);
}
END_TEST

START_TEST(my_mul_num_kar_test_1) {
  matrix_t A, result, res_origin;
  double num = 2.0;
  int res_for_sravn_test_origin = 0;
  int res_for_sravn_test_1 = my_create_matrix(5, 4, &A);
  int res_for_sravn_test_3 = my_create_matrix(5, 4, &res_origin);
  A.matrix[0][0] = 2;
  A.matrix[0][1] = 5;
  A.matrix[0][2] = 7;
  A.matrix[0][3] = -4;
  A.matrix[1][0] = 6;
  A.matrix[1][1] = 3;
  A.matrix[1][2] = 4;
  A.matrix[1][3] = 14;
  A.matrix[2][0] = 5;
  A.matrix[2][1] = -2;
  A.matrix[2][2] = -3;
  A.matrix[2][3] = -1;
  A.matrix[3][0] = 10;
  A.matrix[3][1] = 3;
  A.matrix[3][2] = 9;
  A.matrix[3][3] = -3;
  A.matrix[4][0] = -3;
  A.matrix[4][1] = 3;
  A.matrix[4][2] = 1;
  A.matrix[4][3] = 5;
  res_origin.matrix[0][0] = 4;
  res_origin.matrix[0][1] = 10;
  res_origin.matrix[0][2] = 14;
  res_origin.matrix[0][3] = -8;
  res_origin.matrix[1][0] = 12;
  res_origin.matrix[1][1] = 6;
  res_origin.matrix[1][2] = 8;
  res_origin.matrix[1][3] = 28;
  res_origin.matrix[2][0] = 10;
  res_origin.matrix[2][1] = -4;
  res_origin.matrix[2][2] = -6;
  res_origin.matrix[2][3] = -2;
  res_origin.matrix[3][0] = 20;
  res_origin.matrix[3][1] = 6;
  res_origin.matrix[3][2] = 18;
  res_origin.matrix[3][3] = -6;
  res_origin.matrix[4][0] = -6;
  res_origin.matrix[4][1] = 6;
  res_origin.matrix[4][2] = 2;
  res_origin.matrix[4][3] = 10;
  int res_for_sravn_test = my_mult_number(&A, num, &result);
  ck_assert_int_eq(res_for_sravn_test_1, res_for_sravn_test_origin);
  ck_assert_int_eq(res_for_sravn_test_3, res_for_sravn_test_origin);
  ck_assert_int_eq(res_for_sravn_test, res_for_sravn_test_origin);
  for (int i = 0; i < res_origin.rows; i++) {
    for (int j = 0; j < res_origin.columns; j++) {
      ck_assert_uint_eq(res_origin.matrix[i][j], result.matrix[i][j]);
    }
  }
  my_remove_matrix(&A);
  my_remove_matrix(&result);
  my_remove_matrix(&res_origin);
}
END_TEST

START_TEST(my_mul_num_kar_test_2) {
  matrix_t A, result, res_origin;
  double num = 4.25;
  int res_for_sravn_test_origin = 0;
  int res_for_sravn_test_1 = my_create_matrix(5, 4, &A);
  int res_for_sravn_test_3 = my_create_matrix(5, 4, &res_origin);
  A.matrix[0][0] = 2;
  A.matrix[0][1] = 5;
  A.matrix[0][2] = 7;
  A.matrix[0][3] = -4;
  A.matrix[1][0] = 6;
  A.matrix[1][1] = 3;
  A.matrix[1][2] = 4;
  A.matrix[1][3] = 14;
  A.matrix[2][0] = 5;
  A.matrix[2][1] = -2;
  A.matrix[2][2] = -3;
  A.matrix[2][3] = -1;
  A.matrix[3][0] = 10;
  A.matrix[3][1] = 3;
  A.matrix[3][2] = 9;
  A.matrix[3][3] = -3;
  A.matrix[4][0] = -3;
  A.matrix[4][1] = 3;
  A.matrix[4][2] = 1;
  A.matrix[4][3] = 5;
  res_origin.matrix[0][0] = 8.5;
  res_origin.matrix[0][1] = 21.25;
  res_origin.matrix[0][2] = 29.75;
  res_origin.matrix[0][3] = -17;
  res_origin.matrix[1][0] = 25.5;
  res_origin.matrix[1][1] = 12.75;
  res_origin.matrix[1][2] = 17;
  res_origin.matrix[1][3] = 59.5;
  res_origin.matrix[2][0] = 21.25;
  res_origin.matrix[2][1] = -8.5;
  res_origin.matrix[2][2] = -12.75;
  res_origin.matrix[2][3] = -4.25;
  res_origin.matrix[3][0] = 42.5;
  res_origin.matrix[3][1] = 12.75;
  res_origin.matrix[3][2] = 38.25;
  res_origin.matrix[3][3] = -12.75;
  res_origin.matrix[4][0] = -12.75;
  res_origin.matrix[4][1] = 12.75;
  res_origin.matrix[4][2] = 4.25;
  res_origin.matrix[4][3] = 21.25;
  int res_for_sravn_test = my_mult_number(&A, num, &result);
  ck_assert_int_eq(res_for_sravn_test_1, res_for_sravn_test_origin);
  ck_assert_int_eq(res_for_sravn_test_3, res_for_sravn_test_origin);
  ck_assert_int_eq(res_for_sravn_test, res_for_sravn_test_origin);
  for (int i = 0; i < res_origin.rows; i++) {
    for (int j = 0; j < res_origin.columns; j++) {
      ck_assert_uint_eq(res_origin.matrix[i][j], result.matrix[i][j]);
    }
  }
  my_remove_matrix(&A);
  my_remove_matrix(&result);
  my_remove_matrix(&res_origin);
}
END_TEST

START_TEST(my_transp_kartest_1) {
  matrix_t example;
  matrix_t r;
  matrix_t origin;
  int res_for_sravn_test_origin = 0;
  int res_for_sravn_test_1 = my_create_matrix(3, 2, &example);
  int res_for_sravn_test_2 = my_create_matrix(2, 3, &origin);
  example.matrix[0][0] = 1;
  example.matrix[0][1] = 4;
  example.matrix[1][0] = 2;
  example.matrix[1][1] = 5;
  example.matrix[2][0] = 3;
  example.matrix[2][1] = 6;
  origin.matrix[0][0] = 1;
  origin.matrix[0][1] = 2;
  origin.matrix[0][2] = 3;
  origin.matrix[1][0] = 4;
  origin.matrix[1][1] = 5;
  origin.matrix[1][2] = 6;
  int result = my_transpose(&example, &r);
  ck_assert_int_eq(res_for_sravn_test_1, res_for_sravn_test_origin);
  ck_assert_int_eq(res_for_sravn_test_2, res_for_sravn_test_origin);
  ck_assert_int_eq(result, res_for_sravn_test_origin);
  for (int i = 0; i < r.rows; i++) {
    for (int j = 0; j < r.columns; j++) {
      ck_assert_double_eq_tol(origin.matrix[i][j], r.matrix[i][j], MY_EPS);
    }
  }
  my_remove_matrix(&example);
  my_remove_matrix(&r);
  my_remove_matrix(&origin);
}
END_TEST

START_TEST(my_transp_kartest_2) {
  matrix_t example;
  matrix_t r;
  matrix_t origin;
  int res_for_sravn_test_origin = 0;
  int res_for_sravn_test_1 = my_create_matrix(3, 3, &example);
  int res_for_sravn_test_2 = my_create_matrix(3, 3, &origin);
  example.matrix[0][0] = 1;
  example.matrix[0][1] = 4;
  example.matrix[0][2] = 7;
  example.matrix[1][0] = 2;
  example.matrix[1][1] = 5;
  example.matrix[1][2] = 8;
  example.matrix[2][0] = 3;
  example.matrix[2][1] = 6;
  example.matrix[2][2] = 9;
  origin.matrix[0][0] = 1;
  origin.matrix[0][1] = 2;
  origin.matrix[0][2] = 3;
  origin.matrix[1][0] = 4;
  origin.matrix[1][1] = 5;
  origin.matrix[1][2] = 6;
  origin.matrix[2][0] = 7;
  origin.matrix[2][1] = 8;
  origin.matrix[2][2] = 9;
  int result = my_transpose(&example, &r);
  ck_assert_int_eq(res_for_sravn_test_1, res_for_sravn_test_origin);
  ck_assert_int_eq(res_for_sravn_test_2, res_for_sravn_test_origin);
  ck_assert_int_eq(result, res_for_sravn_test_origin);
  for (int i = 0; i < r.rows; i++) {
    for (int j = 0; j < r.columns; j++) {
      ck_assert_double_eq_tol(origin.matrix[i][j], r.matrix[i][j], MY_EPS);
    }
  }
  my_remove_matrix(&example);
  my_remove_matrix(&r);
  my_remove_matrix(&origin);
}
END_TEST

START_TEST(my_transp_kartest_3) {
  matrix_t example;
  matrix_t r;
  matrix_t origin;
  int res_for_sravn_test_origin = 0;
  int res_for_sravn_test_1 = my_create_matrix(1, 1, &example);
  int res_for_sravn_test_2 = my_create_matrix(1, 1, &origin);
  example.matrix[0][0] = 1.1;
  origin.matrix[0][0] = 1.1;
  int result = my_transpose(&example, &r);
  ck_assert_int_eq(res_for_sravn_test_1, res_for_sravn_test_origin);
  ck_assert_int_eq(res_for_sravn_test_2, res_for_sravn_test_origin);
  ck_assert_int_eq(result, res_for_sravn_test_origin);
  for (int i = 0; i < r.rows; i++) {
    for (int j = 0; j < r.columns; j++) {
      ck_assert_double_eq_tol(origin.matrix[i][j], r.matrix[i][j], MY_EPS);
    }
  }
  my_remove_matrix(&example);
  my_remove_matrix(&r);
  my_remove_matrix(&origin);
}
END_TEST

START_TEST(my_transp_kar_test_1) {
  matrix_t A, result, result_origin;
  my_create_matrix(5, 4, &A);
  my_create_matrix(4, 5, &result_origin);
  A.matrix[0][0] = 2;
  A.matrix[0][1] = 5;
  A.matrix[0][2] = 7;
  A.matrix[0][3] = -4;
  A.matrix[1][0] = 6;
  A.matrix[1][1] = 3;
  A.matrix[1][2] = 4;
  A.matrix[1][3] = 14;
  A.matrix[2][0] = 5;
  A.matrix[2][1] = -2;
  A.matrix[2][2] = -3;
  A.matrix[2][3] = -1;
  A.matrix[3][0] = 10;
  A.matrix[3][1] = 3;
  A.matrix[3][2] = 9;
  A.matrix[3][3] = -3;
  A.matrix[4][0] = -3;
  A.matrix[4][1] = 3;
  A.matrix[4][2] = 1;
  A.matrix[4][3] = 5;
  result_origin.matrix[0][0] = 2;
  result_origin.matrix[0][1] = 6;
  result_origin.matrix[0][2] = 5;
  result_origin.matrix[0][3] = 10;
  result_origin.matrix[0][4] = -3;
  result_origin.matrix[1][0] = 5;
  result_origin.matrix[1][1] = 3;
  result_origin.matrix[1][2] = -2;
  result_origin.matrix[1][3] = 3;
  result_origin.matrix[1][4] = 3;
  result_origin.matrix[2][0] = 7;
  result_origin.matrix[2][1] = 4;
  result_origin.matrix[2][2] = -3;
  result_origin.matrix[2][3] = 9;
  result_origin.matrix[2][4] = 1;
  result_origin.matrix[3][0] = -4;
  result_origin.matrix[3][1] = 14;
  result_origin.matrix[3][2] = -1;
  result_origin.matrix[3][3] = -3;
  result_origin.matrix[3][4] = 5;
  my_transpose(&A, &result);
  for (int i = 0; i < result_origin.rows; i++) {
    for (int j = 0; j < result_origin.columns; j++) {
      ck_assert_uint_eq(result_origin.matrix[i][j], result.matrix[i][j]);
    }
  }
  my_remove_matrix(&A);
  my_remove_matrix(&result);
  my_remove_matrix(&result_origin);
}
END_TEST

START_TEST(my_transp_kar_test_2) {
  matrix_t A, result, res_origin;
  my_create_matrix(4, 7, &A);
  my_create_matrix(7, 4, &res_origin);
  for (int i = 0; i < A.rows; i++) {
    for (int j = 0; j < A.columns; j++) {
      A.matrix[i][j] = i;
    }
  }
  for (int i = 0; i < res_origin.rows; i++) {
    for (int j = 0; j < res_origin.columns; j++) {
      res_origin.matrix[i][j] = j;
    }
  }
  my_transpose(&A, &result);
  for (int i = 0; i < res_origin.rows; i++) {
    for (int j = 0; j < res_origin.columns; j++) {
      ck_assert_uint_eq(res_origin.matrix[i][j], result.matrix[i][j]);
    }
  }
  my_remove_matrix(&A);
  my_remove_matrix(&result);
  my_remove_matrix(&res_origin);
}
END_TEST

START_TEST(my_transp_kar_test_3) {
  matrix_t A, result;
  my_create_matrix(4, -7, &A);
  int res_for_sravn_test = my_transpose(&A, &result);
  int res_for_sravn_test_origin = 1;
  ck_assert_uint_eq(res_for_sravn_test, res_for_sravn_test_origin);
  my_remove_matrix(&result);
  my_remove_matrix(&A);
}
END_TEST

START_TEST(my_mult_kartest_1) {
  matrix_t A, B, result, res_origin;
  int res_for_sravn_test_origin = 0;
  int res_for_sravn_test_1 = my_create_matrix(5, 4, &A);
  int res_for_sravn_test_2 = my_create_matrix(4, 4, &B);
  int res_for_sravn_test_4 = my_create_matrix(5, 4, &res_origin);
  A.matrix[0][0] = 2;
  A.matrix[0][1] = 5;
  A.matrix[0][2] = 7;
  A.matrix[0][3] = -4;
  A.matrix[1][0] = 6;
  A.matrix[1][1] = 3;
  A.matrix[1][2] = 4;
  A.matrix[1][3] = 14;
  A.matrix[2][0] = 5;
  A.matrix[2][1] = -2;
  A.matrix[2][2] = -3;
  A.matrix[2][3] = -1;
  A.matrix[3][0] = 10;
  A.matrix[3][1] = 3;
  A.matrix[3][2] = 9;
  A.matrix[3][3] = -3;
  A.matrix[4][0] = -3;
  A.matrix[4][1] = 3;
  A.matrix[4][2] = 1;
  A.matrix[4][3] = 5;
  B.matrix[0][0] = 8;
  B.matrix[0][1] = 8;
  B.matrix[0][2] = 3;
  B.matrix[0][3] = 5;
  B.matrix[1][0] = -7;
  B.matrix[1][1] = 7;
  B.matrix[1][2] = 1;
  B.matrix[1][3] = 1;
  B.matrix[2][0] = 7;
  B.matrix[2][1] = 3;
  B.matrix[2][2] = 4;
  B.matrix[2][3] = -4;
  B.matrix[3][0] = 10;
  B.matrix[3][1] = 3;
  B.matrix[3][2] = 9;
  B.matrix[3][3] = -3;
  res_origin.matrix[0][0] = -10;
  res_origin.matrix[0][1] = 60;
  res_origin.matrix[0][2] = 3;
  res_origin.matrix[0][3] = -1;
  res_origin.matrix[1][0] = 195;
  res_origin.matrix[1][1] = 123;
  res_origin.matrix[1][2] = 163;
  res_origin.matrix[1][3] = -25;
  res_origin.matrix[2][0] = 23;
  res_origin.matrix[2][1] = 14;
  res_origin.matrix[2][2] = -8;
  res_origin.matrix[2][3] = 38;
  res_origin.matrix[3][0] = 92;
  res_origin.matrix[3][1] = 119;
  res_origin.matrix[3][2] = 42;
  res_origin.matrix[3][3] = 26;
  res_origin.matrix[4][0] = 12;
  res_origin.matrix[4][1] = 15;
  res_origin.matrix[4][2] = 43;
  res_origin.matrix[4][3] = -31;
  int res_for_sravn_test = my_mult_matrix(&A, &B, &result);
  ck_assert_int_eq(res_for_sravn_test_1, res_for_sravn_test_origin);
  ck_assert_int_eq(res_for_sravn_test_2, res_for_sravn_test_origin);
  ck_assert_int_eq(res_for_sravn_test_4, res_for_sravn_test_origin);
  ck_assert_int_eq(res_for_sravn_test, res_for_sravn_test_origin);
  for (int i = 0; i < res_origin.rows; i++) {
    for (int j = 0; j < res_origin.columns; j++) {
      ck_assert_uint_eq(res_origin.matrix[i][j], result.matrix[i][j]);
    }
  }
  my_remove_matrix(&A);
  my_remove_matrix(&B);
  my_remove_matrix(&result);
  my_remove_matrix(&res_origin);
}
END_TEST

START_TEST(my_mult_kartest_2) {
  matrix_t A, B, result, res_origin;
  int res_for_sravn_test_origin = 0;
  int res_for_sravn_test_1 = my_create_matrix(2, 2, &A);
  int res_for_sravn_test_2 = my_create_matrix(2, 4, &B);
  int res_for_sravn_test_4 = my_create_matrix(2, 4, &res_origin);
  A.matrix[0][0] = 2.987654;
  A.matrix[0][1] = -5.3456;
  A.matrix[1][0] = 6.23;
  A.matrix[1][1] = -3.9292;
  B.matrix[0][0] = 4.838;
  B.matrix[0][1] = 8.0987;
  B.matrix[0][2] = 8.09;
  B.matrix[0][3] = -987;
  B.matrix[1][0] = -8;
  B.matrix[1][1] = -0.921;
  B.matrix[1][2] = -0.91;
  B.matrix[1][3] = 21;
  res_origin.matrix[0][0] = 57.219070052;
  res_origin.matrix[0][1] = 29.1194110498;
  res_origin.matrix[0][2] = 29.03461686;
  res_origin.matrix[0][3] = -3061.072098;
  res_origin.matrix[1][0] = 61.57434;
  res_origin.matrix[1][1] = 54.0736942;
  res_origin.matrix[1][2] = 53.976272;
  res_origin.matrix[1][3] = -6231.5232;
  int res_for_sravn_test = my_mult_matrix(&A, &B, &result);
  ck_assert_int_eq(res_for_sravn_test_1, res_for_sravn_test_origin);
  ck_assert_int_eq(res_for_sravn_test_2, res_for_sravn_test_origin);
  ck_assert_int_eq(res_for_sravn_test_4, res_for_sravn_test_origin);
  ck_assert_int_eq(res_for_sravn_test, res_for_sravn_test_origin);
  for (int i = 0; i < res_origin.rows; i++) {
    for (int j = 0; j < res_origin.columns; j++) {
      ck_assert_uint_eq(res_origin.matrix[i][j], result.matrix[i][j]);
    }
  }
  my_remove_matrix(&A);
  my_remove_matrix(&B);
  my_remove_matrix(&result);
  my_remove_matrix(&res_origin);
}
END_TEST

START_TEST(my_mult_kartest_3) {
  matrix_t A, B, result, res_origin;
  int res_for_sravn_test_origin = 0;
  int res_for_sravn_test_1 = my_create_matrix(3, 3, &A);
  int res_for_sravn_test_2 = my_create_matrix(3, 3, &B);
  int res_for_sravn_test_4 = my_create_matrix(3, 3, &res_origin);
  A.matrix[0][0] = 0;
  A.matrix[0][1] = 9;
  A.matrix[0][2] = 1;
  A.matrix[1][0] = 1;
  A.matrix[1][1] = 3;
  A.matrix[1][2] = 7;
  A.matrix[2][0] = 2;
  A.matrix[2][1] = 7;
  A.matrix[2][2] = 0;
  B.matrix[0][0] = 0;
  B.matrix[0][1] = 9;
  B.matrix[0][2] = 8;
  B.matrix[1][0] = 0;
  B.matrix[1][1] = 9;
  B.matrix[1][2] = 9;
  B.matrix[2][0] = 1;
  B.matrix[2][1] = 9;
  B.matrix[2][2] = 6;
  res_origin.matrix[0][0] = 1;
  res_origin.matrix[0][1] = 90;
  res_origin.matrix[0][2] = 87;
  res_origin.matrix[1][0] = 7;
  res_origin.matrix[1][1] = 99;
  res_origin.matrix[1][2] = 77;
  res_origin.matrix[2][0] = 0;
  res_origin.matrix[2][1] = 81;
  res_origin.matrix[2][2] = 79;
  int res_for_sravn_test = my_mult_matrix(&A, &B, &result);
  ck_assert_int_eq(res_for_sravn_test_1, res_for_sravn_test_origin);
  ck_assert_int_eq(res_for_sravn_test_2, res_for_sravn_test_origin);
  ck_assert_int_eq(res_for_sravn_test_4, res_for_sravn_test_origin);
  ck_assert_int_eq(res_for_sravn_test, res_for_sravn_test_origin);
  for (int i = 0; i < res_origin.rows; i++) {
    for (int j = 0; j < res_origin.columns; j++) {
      ck_assert_uint_eq(res_origin.matrix[i][j], result.matrix[i][j]);
    }
  }
  my_remove_matrix(&A);
  my_remove_matrix(&B);
  my_remove_matrix(&result);
  my_remove_matrix(&res_origin);
}
END_TEST

START_TEST(my_mult_kartest_4) {
  matrix_t A, B, result;
  int res_for_sravn_test_origin = 2;
  my_create_matrix(2, 3, &A);
  my_create_matrix(4, 2, &B);
  int res_for_sravn_test = my_mult_matrix(&A, &B, &result);
  ck_assert_int_eq(res_for_sravn_test, res_for_sravn_test_origin);
  my_remove_matrix(&A);
  my_remove_matrix(&B);
  my_remove_matrix(&result);
}
END_TEST

START_TEST(my_mult_kartest_5) {
  matrix_t A, B, result;
  int res_for_sravn_test_origin = 0;
  my_create_matrix(2, 3, &A);
  my_create_matrix(3, 12, &B);
  for (int i = 0; i < B.rows; i++) {
    for (int j = 0; j < B.columns; j++) {
      B.matrix[i][j] = i + j;
    }
  }
  int res_for_sravn_test = my_mult_matrix(&A, &B, &result);
  ck_assert_int_eq(res_for_sravn_test, res_for_sravn_test_origin);
  for (int i = 0; i < result.rows; i++) {
    for (int j = 0; j < result.columns; j++) {
      ck_assert_int_eq(result.matrix[i][j], 0.0);
    }
  }
  my_remove_matrix(&A);
  my_remove_matrix(&B);
  my_remove_matrix(&result);
}
END_TEST

START_TEST(my_mult_kartest_6) {
  matrix_t A, B, result;
  int res_for_sravn_test_origin = 1;
  my_create_matrix(-12, 3, &A);
  my_create_matrix(3, 12, &B);
  int res_for_sravn_test = my_mult_matrix(&A, &B, &result);
  ck_assert_int_eq(res_for_sravn_test, res_for_sravn_test_origin);
  my_remove_matrix(&B);
  my_remove_matrix(&result);
}
END_TEST

START_TEST(my_determ_kartest_1) {
  matrix_t A;
  double result = 0;
  my_create_matrix(3, 3, &A);
  A.matrix[0][0] = 1;
  A.matrix[0][1] = 2;
  A.matrix[0][2] = 3;
  A.matrix[1][0] = 5;
  A.matrix[1][1] = 3;
  A.matrix[1][2] = 2;
  A.matrix[2][0] = -5;
  A.matrix[2][1] = 3;
  A.matrix[2][2] = 3;
  int res_for_sravn_test = my_determinant(&A, &result);
  int res_for_sravn_test_origin = 0;
  double result_origin = 43;
  ck_assert_uint_eq(res_for_sravn_test, res_for_sravn_test_origin);
  ck_assert_uint_eq(result, result_origin);
  my_remove_matrix(&A);
}
END_TEST

START_TEST(my_determ_kartest_2) {
  matrix_t A;
  double result = 0;
  my_create_matrix(4, 4, &A);
  A.matrix[0][0] = 1;
  A.matrix[0][1] = 2;
  A.matrix[0][2] = 3;
  A.matrix[0][3] = 3;
  A.matrix[1][0] = 5;
  A.matrix[1][1] = 3;
  A.matrix[1][2] = 2;
  A.matrix[1][3] = 2;
  A.matrix[2][0] = -5;
  A.matrix[2][1] = 3;
  A.matrix[2][2] = 3;
  A.matrix[2][3] = 3;
  A.matrix[3][0] = -12.12;
  A.matrix[3][1] = 12.12;
  A.matrix[3][2] = 2.12;
  A.matrix[3][3] = -2.12;
  int res_for_sravn_test = my_determinant(&A, &result);
  int res_for_sravn_test_origin = 0;
  ck_assert_uint_eq(res_for_sravn_test, res_for_sravn_test_origin);
  my_remove_matrix(&A);
}
END_TEST

START_TEST(my_determ_kartest_3) {
  matrix_t A;
  double result = 0;
  my_create_matrix(1, 1, &A);
  A.matrix[0][0] = 1;
  int res_for_sravn_test = my_determinant(&A, &result);
  int res_for_sravn_test_origin = 0;
  double result_origin = 1;
  ck_assert_uint_eq(res_for_sravn_test, res_for_sravn_test_origin);
  ck_assert_uint_eq(result, result_origin);
  my_remove_matrix(&A);
}
END_TEST

START_TEST(my_determ_kartest_4) {
  matrix_t A;
  double result = 0;
  my_create_matrix(2, 2, &A);
  A.matrix[0][0] = 55.5;
  A.matrix[0][1] = 14.4;
  A.matrix[1][0] = -0.752;
  A.matrix[1][1] = 156.2;
  int res_for_sravn_test = my_determinant(&A, &result);
  int res_for_sravn_test_origin = 0;
  double result_origin = 8679.9288;
  ck_assert_uint_eq(res_for_sravn_test, res_for_sravn_test_origin);
  ck_assert_uint_eq(result, result_origin);
  my_remove_matrix(&A);
}
END_TEST

START_TEST(my_determ_kartest_5) {
  matrix_t A;
  double result = 0;
  my_create_matrix(4, 4, &A);
  A.matrix[0][0] = 11.1;
  A.matrix[0][1] = 2.2;
  A.matrix[0][2] = 3.3;
  A.matrix[0][3] = 4.4;
  A.matrix[1][0] = 8.8;
  A.matrix[1][1] = -9.9;
  A.matrix[1][2] = 10.1;
  A.matrix[1][3] = 11.11;
  A.matrix[2][0] = 15.15;
  A.matrix[2][1] = 16.16;
  A.matrix[2][2] = 17.17;
  A.matrix[2][3] = 18.18;
  A.matrix[3][0] = -22.22;
  A.matrix[3][1] = 23.23;
  A.matrix[3][2] = 24.24;
  A.matrix[3][3] = 25.25;
  int res_for_sravn_test = my_determinant(&A, &result);
  int res_for_sravn_test_origin = 0;
  double result_origin = -11770.2443124;
  ck_assert_uint_eq(res_for_sravn_test, res_for_sravn_test_origin);
  ck_assert_double_eq_tol(result, result_origin, MY_EPS);
  my_remove_matrix(&A);
}
END_TEST

START_TEST(my_determ_kartest_6) {
  matrix_t A;
  double result = 0;
  my_create_matrix(4, 4, &A);
  int res_for_sravn_test = my_determinant(&A, &result);
  int res_for_sravn_test_origin = 0;
  double result_origin = 0;
  ck_assert_uint_eq(res_for_sravn_test, res_for_sravn_test_origin);
  ck_assert_double_eq_tol(result, result_origin, MY_EPS);
  my_remove_matrix(&A);
}
END_TEST

START_TEST(my_determ_kartest_7) {
  matrix_t A;
  double result = 0;
  my_create_matrix(5, 4, &A);
  int res_for_sravn_test = my_determinant(&A, &result);
  int res_for_sravn_test_origin = 2;
  ck_assert_uint_eq(res_for_sravn_test, res_for_sravn_test_origin);
  my_remove_matrix(&A);
}
END_TEST

START_TEST(my_determ_kartest_8) {
  matrix_t A;
  double result = 0;
  my_create_matrix(-4, 4, &A);
  int res_for_sravn_test = my_determinant(&A, &result);
  int res_for_sravn_test_origin = 1;
  ck_assert_uint_eq(res_for_sravn_test, res_for_sravn_test_origin);
  my_remove_matrix(&A);
}
END_TEST

START_TEST(my_calc_compl_kartest_1) {
  matrix_t A, result, res_origin;
  my_create_matrix(3, 3, &A);
  my_create_matrix(3, 3, &res_origin);
  A.matrix[0][0] = 1;
  A.matrix[0][1] = 2;
  A.matrix[0][2] = 3;
  A.matrix[1][0] = 0;
  A.matrix[1][1] = 4;
  A.matrix[1][2] = 2;
  A.matrix[2][0] = 5;
  A.matrix[2][1] = 2;
  A.matrix[2][2] = 1;
  res_origin.matrix[0][0] = 0;
  res_origin.matrix[0][1] = 10;
  res_origin.matrix[0][2] = -20;
  res_origin.matrix[1][0] = 4;
  res_origin.matrix[1][1] = -14;
  res_origin.matrix[1][2] = 8;
  res_origin.matrix[2][0] = -8;
  res_origin.matrix[2][1] = -2;
  res_origin.matrix[2][2] = 4;
  my_calc_complements(&A, &result);
  for (int i = 0; i < res_origin.rows; i++) {
    for (int j = 0; j < res_origin.columns; j++) {
      ck_assert_uint_eq(res_origin.matrix[i][j], result.matrix[i][j]);
    }
  }
  my_remove_matrix(&A);
  my_remove_matrix(&result);
  my_remove_matrix(&res_origin);
}
END_TEST

START_TEST(my_calc_compl_kartest_2) {
  matrix_t A, result, res_origin;
  my_create_matrix(2, 2, &A);
  my_create_matrix(2, 2, &res_origin);
  A.matrix[0][0] = 2;
  A.matrix[0][1] = 4;
  A.matrix[1][0] = 6;
  A.matrix[1][1] = 3;
  res_origin.matrix[0][0] = 3;
  res_origin.matrix[0][1] = -6;
  res_origin.matrix[1][0] = -4;
  res_origin.matrix[1][1] = 2;
  my_calc_complements(&A, &result);
  for (int i = 0; i < res_origin.rows; i++) {
    for (int j = 0; j < res_origin.columns; j++) {
      ck_assert_uint_eq(res_origin.matrix[i][j], result.matrix[i][j]);
    }
  }
  my_remove_matrix(&A);
  my_remove_matrix(&result);
  my_remove_matrix(&res_origin);
}
END_TEST

START_TEST(my_calc_compl_kartest_2_0) {
  matrix_t A, result, res_origin;
  my_create_matrix(-2, 0, &A);
  my_create_matrix(2, 2, &res_origin);

  int result_res = my_calc_complements(&A, &result);
  int resultat_origin = 1;
  ck_assert_uint_eq(resultat_origin, result_res);
  my_remove_matrix(&A);
  my_remove_matrix(&result);
  my_remove_matrix(&res_origin);
}
END_TEST

START_TEST(my_calc_compl_kartest_3) {
  matrix_t A, result, res_origin;
  my_create_matrix(-2, 2, &A);
  my_create_matrix(2, 2, &res_origin);
  int res_for_sravn_test = my_calc_complements(&A, &result);
  int res_for_sravn_test_origin = 1;
  ck_assert_uint_eq(res_for_sravn_test, res_for_sravn_test_origin);
  my_remove_matrix(&A);
  my_remove_matrix(&result);
  my_remove_matrix(&res_origin);
}
END_TEST

START_TEST(my_calc_compl_kartest_4) {
  matrix_t A, result, res_origin;
  my_create_matrix(2, 4, &A);
  my_create_matrix(2, 2, &res_origin);
  int res_for_sravn_test = my_calc_complements(&A, &result);
  int res_for_sravn_test_origin = 2;
  ck_assert_uint_eq(res_for_sravn_test, res_for_sravn_test_origin);
  my_remove_matrix(&A);
  my_remove_matrix(&result);
  my_remove_matrix(&res_origin);
}
END_TEST

START_TEST(my_inverse_kartest_1) {
  matrix_t A, result, res_origin;
  my_create_matrix(3, 3, &A);
  my_create_matrix(3, 3, &res_origin);
  A.matrix[0][0] = 2;
  A.matrix[0][1] = 1.3;
  A.matrix[0][2] = 0.7;
  A.matrix[1][0] = -1;
  A.matrix[1][1] = 0;
  A.matrix[1][2] = 3;
  A.matrix[2][0] = 0.3;
  A.matrix[2][1] = -0.3;
  A.matrix[2][2] = 2;
  res_origin.matrix[0][0] = 45.0 / 289.0;
  res_origin.matrix[0][1] = -281.0 / 578.0;
  res_origin.matrix[0][2] = 195.0 / 289.0;
  res_origin.matrix[1][0] = 145.0 / 289.0;
  res_origin.matrix[1][1] = 379.0 / 578.0;
  res_origin.matrix[1][2] = -335.0 / 289.0;
  res_origin.matrix[2][0] = 15.0 / 289.0;
  res_origin.matrix[2][1] = 99.0 / 578.0;
  res_origin.matrix[2][2] = 65.0 / 289.0;
  my_inverse_matrix(&A, &result);
  for (int i = 0; i < res_origin.rows; i++) {
    for (int j = 0; j < res_origin.columns; j++) {
      ck_assert_double_eq_tol(result.matrix[i][j], res_origin.matrix[i][j],
                              MY_EPS);
    }
  }
  my_remove_matrix(&A);
  my_remove_matrix(&result);
  my_remove_matrix(&res_origin);
}
END_TEST

START_TEST(my_inverse_kartest_2) {
  matrix_t A, result, res_origin;
  my_create_matrix(3, 3, &A);
  my_create_matrix(3, 3, &res_origin);
  A.matrix[0][0] = 2.8;
  A.matrix[0][1] = 1.3;
  A.matrix[0][2] = 7.01;
  A.matrix[1][0] = -1.03;
  A.matrix[1][1] = -2.3;
  A.matrix[1][2] = 3.01;
  A.matrix[2][0] = 0;
  A.matrix[2][1] = -3;
  A.matrix[2][2] = 2;
  res_origin.matrix[0][0] = 44300.0 / 367429.0;
  res_origin.matrix[0][1] = -236300.0 / 367429.0;
  res_origin.matrix[0][2] = 200360.0 / 367429.0;
  res_origin.matrix[1][0] = 20600.0 / 367429.0;
  res_origin.matrix[1][1] = 56000.0 / 367429.0;
  res_origin.matrix[1][2] = -156483.0 / 367429.0;
  res_origin.matrix[2][0] = 30900.0 / 367429.0;
  res_origin.matrix[2][1] = 84000.0 / 367429.0;
  res_origin.matrix[2][2] = -51010.0 / 367429.0;
  my_inverse_matrix(&A, &result);
  for (int i = 0; i < res_origin.rows; i++) {
    for (int j = 0; j < res_origin.columns; j++) {
      ck_assert_double_eq_tol(result.matrix[i][j], res_origin.matrix[i][j],
                              MY_EPS);
    }
  }
  my_remove_matrix(&A);
  my_remove_matrix(&result);
  my_remove_matrix(&res_origin);
}
END_TEST

START_TEST(my_inverse_kartest_3) {
  matrix_t A, result, res_origin;
  my_create_matrix(1, 1, &A);
  my_create_matrix(1, 1, &res_origin);
  A.matrix[0][0] = 777;
  res_origin.matrix[0][0] = 1.0 / 777.0;
  int res_for_sravn_test = my_inverse_matrix(&A, &result);
  int res_for_sravn_test_origin = 0;
  ck_assert_double_eq_tol(res_origin.matrix[0][0], result.matrix[0][0], MY_EPS);
  ck_assert_uint_eq(res_for_sravn_test, res_for_sravn_test_origin);
  my_remove_matrix(&A);
  my_remove_matrix(&result);
  my_remove_matrix(&res_origin);
}
END_TEST

START_TEST(my_inverse_kartest_4) {
  matrix_t A, result;
  my_create_matrix(-5, 5, &A);
  int res_for_sravn_test = my_inverse_matrix(&A, &result);
  int res_for_sravn_test_origin = 1;
  ck_assert_uint_eq(res_for_sravn_test, res_for_sravn_test_origin);
  my_remove_matrix(&A);
  my_remove_matrix(&result);
}
END_TEST

START_TEST(my_inverse_kartest_5) {
  matrix_t A, result;
  my_create_matrix(1, 2, &A);
  A.matrix[0][0] = 777;
  A.matrix[0][1] = 777;
  int res_for_sravn_test = my_inverse_matrix(&A, &result);
  int res_for_sravn_test_origin = 2;
  ck_assert_uint_eq(res_for_sravn_test, res_for_sravn_test_origin);
  my_remove_matrix(&A);
  my_remove_matrix(&result);
}
END_TEST

START_TEST(my_inverse_kartest_6) {
  matrix_t A, result;
  my_create_matrix(3, 3, &A);
  A.matrix[0][0] = 0;
  A.matrix[0][1] = 0;
  A.matrix[0][2] = 0;
  A.matrix[1][0] = 0;
  A.matrix[1][1] = 0;
  A.matrix[1][2] = 0;
  A.matrix[2][0] = 0;
  A.matrix[2][1] = 0;
  A.matrix[2][2] = 0;
  int res_for_sravn_test = my_inverse_matrix(&A, &result);
  int res_for_sravn_test_origin = 2;
  ck_assert_uint_eq(res_for_sravn_test, res_for_sravn_test_origin);
  my_remove_matrix(&A);
  my_remove_matrix(&result);
}
END_TEST

START_TEST(my_remove_kartest_1) {
  matrix_t A;
  my_create_matrix(3, 3, &A);
  A.matrix[0][0] = 75301501;
  my_remove_matrix(&A);
  int res_for_sravn_test = (A.rows == 3) ? 0 : 1;
  int res_for_sravn_test_origin = 1;
  ck_assert_uint_eq(res_for_sravn_test, res_for_sravn_test_origin);
}
END_TEST

void srunner_add_eq_testa(SRunner *sr) {
  Suite *s1 = suite_create("A-kar");
  TCase *tc1_1 = tcase_create("A-kar");

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, my_create_kartest_1);
  tcase_add_test(tc1_1, my_create_kartest_2);
  tcase_add_test(tc1_1, my_create_kartest_3);
  tcase_add_test(tc1_1, my_create_kartest_4);
  tcase_add_test(tc1_1, my_create_kartest_5);
  tcase_add_test(tc1_1, my_eq_kartest_1);
  tcase_add_test(tc1_1, my_eq_kartest_2);
  tcase_add_test(tc1_1, my_eq_kartest_3);
  tcase_add_test(tc1_1, my_eq_kartest_4);
  tcase_add_test(tc1_1, my_eq_kar_test_1);
  tcase_add_test(tc1_1, my_eq_kar_test_2);
  tcase_add_test(tc1_1, my_eq_kar_test_3);
  tcase_add_test(tc1_1, my_eq_kar_test_4);
  tcase_add_test(tc1_1, my_eq_kar_test_5);
  tcase_add_test(tc1_1, my_eq_kar_test_6);
  tcase_add_test(tc1_1, my_sum_kartest_1);
  tcase_add_test(tc1_1, my_sum_kartest_1_0);
  tcase_add_test(tc1_1, my_sum_kartest_2);
  tcase_add_test(tc1_1, my_sum_kartest_3);
  tcase_add_test(tc1_1, my_sum_kar_test_1);
  tcase_add_test(tc1_1, my_sum_kar_test_2);
  tcase_add_test(tc1_1, my_sum_kar_test_3);
  tcase_add_test(tc1_1, my_sum_kar_test_4);
  tcase_add_test(tc1_1, my_sum_kar_test_5);
  tcase_add_test(tc1_1, my_sum_kar_test_6);
  tcase_add_test(tc1_1, my_sum_kar_test_7);
  tcase_add_test(tc1_1, my_sum_kar_test_8);
  tcase_add_test(tc1_1, my_sub_kartest_1);
  tcase_add_test(tc1_1, my_sub_kartest_2);
  tcase_add_test(tc1_1, my_sub_kartest_3);
  tcase_add_test(tc1_1, my_sub_kartest_4);
  tcase_add_test(tc1_1, my_sub_kar_test_1);
  tcase_add_test(tc1_1, my_sub_kar_test_2);
  tcase_add_test(tc1_1, my_sub_kar_test_3);
  tcase_add_test(tc1_1, my_sub_kar_test_4);
  tcase_add_test(tc1_1, my_sub_kar_test_5);
  tcase_add_test(tc1_1, my_sub_kar_test_6);
  tcase_add_test(tc1_1, my_sub_kar_test_7);
  tcase_add_test(tc1_1, my_sub_kar_test_8);
  tcase_add_test(tc1_1, my_sub_kar_test_9);
  tcase_add_test(tc1_1, my_mul_num_kartest_1);
  tcase_add_test(tc1_1, my_mul_num_kartest_1_0);
  tcase_add_test(tc1_1, my_mul_num_kartest_2);
  tcase_add_test(tc1_1, my_mul_num_kartest_3);
  tcase_add_test(tc1_1, my_mul_num_kar_test_1);
  tcase_add_test(tc1_1, my_mul_num_kar_test_2);
  tcase_add_test(tc1_1, my_transp_kartest_1);
  tcase_add_test(tc1_1, my_transp_kartest_2);
  tcase_add_test(tc1_1, my_transp_kartest_3);
  tcase_add_test(tc1_1, my_transp_kar_test_1);
  tcase_add_test(tc1_1, my_transp_kar_test_2);
  tcase_add_test(tc1_1, my_transp_kar_test_3);
  tcase_add_test(tc1_1, my_mult_kartest_1);
  tcase_add_test(tc1_1, my_mult_kartest_2);
  tcase_add_test(tc1_1, my_mult_kartest_3);
  tcase_add_test(tc1_1, my_mult_kartest_4);
  tcase_add_test(tc1_1, my_mult_kartest_5);
  tcase_add_test(tc1_1, my_mult_kartest_6);
  tcase_add_test(tc1_1, my_determ_kartest_1);
  tcase_add_test(tc1_1, my_determ_kartest_2);
  tcase_add_test(tc1_1, my_determ_kartest_3);
  tcase_add_test(tc1_1, my_determ_kartest_4);
  tcase_add_test(tc1_1, my_determ_kartest_5);
  tcase_add_test(tc1_1, my_determ_kartest_6);
  tcase_add_test(tc1_1, my_determ_kartest_7);
  tcase_add_test(tc1_1, my_determ_kartest_8);
  tcase_add_test(tc1_1, my_calc_compl_kartest_1);
  tcase_add_test(tc1_1, my_calc_compl_kartest_2);
  tcase_add_test(tc1_1, my_calc_compl_kartest_2_0);
  tcase_add_test(tc1_1, my_calc_compl_kartest_3);
  tcase_add_test(tc1_1, my_calc_compl_kartest_4);
  tcase_add_test(tc1_1, my_inverse_kartest_1);
  tcase_add_test(tc1_1, my_inverse_kartest_2);
  tcase_add_test(tc1_1, my_inverse_kartest_3);
  tcase_add_test(tc1_1, my_inverse_kartest_4);
  tcase_add_test(tc1_1, my_inverse_kartest_5);
  tcase_add_test(tc1_1, my_inverse_kartest_6);
  tcase_add_test(tc1_1, my_remove_kartest_1);

  srunner_add_suite(sr, s1);
}

int main(void) {
  Suite *s = suite_create("matrix karleenk");
  SRunner *sr = srunner_create(s);
  int res = 0;

  srunner_add_eq_testa(sr);
  srunner_set_fork_status(sr, CK_NOFORK);
  srunner_run_all(sr, CK_ENV);
  res = srunner_ntests_failed(sr);
  srunner_free(sr);

  return res == 0 ? 0 : 1;
}
